# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 2) do

  create_table "authors", :force => true do |t|
    t.column "name", :string
  end

  create_table "books", :force => true do |t|
    t.column "ean",         :string
    t.column "title",       :string
    t.column "description", :text
  end

end
